name: si_build

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - id: Begin
        name: Begin
        run: |
          echo "Begin ${GITHUB_WORKFLOW}/${GITHUB_JOB}"

      - id: Checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: Install_apt
        name: Install_apt
        run: |
          sudo apt update -y
          sudo apt-get install -y $(cat build_tools/ubuntu.deps)

      - id: Submodule_init_recursive
        name: Submodule_init_recursive
        run: |
          git submodule update --init --recursive

      - id: Build_third_party_masstree
        name: Build_third_party_masstree
        run: |
          cd third_party/masstree
          ./bootstrap.sh
          ./configure
          make -j CXXFLAGS='-g -W -Wall -O3 -fPIC'
          ar cr libkohler_masstree_json.a json.o string.o straccum.o str.o msgpack.o clp.o kvrandom.o compiler.o memdebug.o kvthread.o misc.o
          ranlib libkohler_masstree_json.a

      - id: Build_third_party_mimalloc
        name: Build_third_party_mimalloc
        run: |
          cd third_party/mimalloc
          mkdir -p out/release
          cd out/release
          cmake ../..
          make all -j

      - id: Build_third_party_googletest
        name: Build_third_party_googletest
        run: |
          cd third_party/googletest
          mkdir -p build
          cd build
          cmake ..
          make -j

      - id: Build_si
        name: Build_si
        run: |
          cd si
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j
